### ISSUE TITLE
Unable to load Forklift.dll with 1.0.6b and latest special k

### ISSUE THREAD

**Issue by soredake** [Raymonf/Forklift#3]
![изображение](https://user-images.githubusercontent.com/5204968/178732157-641ebd79-0226-4108-adc9-ffd2be40bbd4.png)

**Comment by soredake** [comment]
Works fine with 1.0.6

**Comment by Raymonf** [comment]
Do you have the Visual C++ redistributable package installed?

https://aka.ms/vs/17/release/vc_redist.x64.exe

「soredake ***@***.***>」在 2022年7月13日 週三，上午8:21 寫道：

**Comment by soredake** [comment]
Yes, it's installed, 2015-2022 version.

**Comment by Raymonf** [comment]
In that case, I suggest waiting for v1.0.7 and trying again when that comes
out. LemonHaze did a bunch of cool things, so I'll release a version with
those changes as soon as I have a chance to work on Forklift again.

By the way, the only major change from v1.0.6 -> v1.0.6b is switching to
the v143 (VC++ 2022) compiler from v141 (VC++ 2017). You could try
repairing the installation with the version downloaded from the link above,
but I have no other suggestions because the message doesn't give an error
code.

**Comment by LemonHaze420** [comment]
I have a couple things planned and then I will be good to release. I spotted this firstly on Shenmue Dojo forums, so I was a bit late to it. But I should have a version which will work for all.



> Yes, it's installed, 2015-2022 version.

Just to rule out what @Raymonf has suggested, to rule out dependencies being the issue, can you please ensure you have fully updated your machine, run a repair installation of the previously linked (https://aka.ms/vs/17/release/vc_redist.x64.exe) redistributable package and report back whether it fixes anything @soredake?

**Comment by soredake** [comment]
@LemonHaze420 all updates are installed, repaired & rebooted, still seeing error. Windows 11 Pro if that matters.

**Comment by LemonHaze420** [comment]
Thanks for your quick response, can you try this version @soredake?

[Forklift.zip](https://github.com/Raymonf/Forklift/files/9141782/Forklift.zip)

**Comment by soredake** [comment]
Unpacked 1.0.6b and then this dll, no error now, thanks.

**Comment by LemonHaze420** [comment]
> Unpacked 1.0.6b and then this dll, no error now, thanks.

Great, thanks for the confirmation. Keep checking back for the public version.

**Comment by LemonHaze420** [comment]
@Raymonf 

For future reference, it looks like a debug/msvcrtd thing.

**Comment by LemonHaze420** [comment]
Latest changes should have all fixes. Closing.

**Comment by Raymonf** [comment]
https://github.com/Raymonf/Forklift/releases/tag/v1.1.0 is out officially now, sorry for the long delay :)
